spring:
  application:
    name: discovery-service

server:
  port: 8761

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      default: http://localhost:8761/eureka/